version: '3'

services:
  db:
    image: mysql:8.0.33
    restart: always
    env_file:
      - path: ./env/.env
        required: true
    # 자동으로 environment 변수를 인식해줌.
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_USER_HOST
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --init-connect='SET NAMES utf8mb4'

    ports:      
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-logs:/var/log/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - path: ./env/.env
        required: true
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DB_NAME
      - DB_HOST=db
    
    restart: always
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - app_log:/app/log

volumes:
  app_log:
  db-data:
  db-logs:

      