version: '3'

services:
  db:
    image: mysql:8.0.33
    restart: always
    env_file:
      - path: ./env/.env
        required: true
    # 자동으로 environment 변수를 인식해줌.
    # environment:
    #   - MYSQL_ROOT_PASSWORD
    #   - MYSQL_USER
    #   - MYSQL_PASSWORD

    ports:      
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-logs:/var/log/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - path: ./env/.env
        required: true
    environment:
      - DEV_DB_USER
      - DEV_DB_PASSWORD
      - DEV_DB_PORT
      - DEV_DB_NAME
      - DEV_DB_HOST=db
    
    restart: always
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - app_log:/app/log

volumes:
  app_log:
  db-data:
  db-logs:

      