apiVersion: v1
kind: Service
metadata:
  name: honeycomb-service
spec:
  selector:
    app: honeycomb-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeycomb-app
spec:
  selector:
    matchLabels:
      app: honeycomb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: honeycomb-app
    spec:
      containers:
        - name: honeycomb-app
          image: ket0825/honeycomb-app:1.0.0
          envFrom:
            - configMapRef:
                name: honeycomb-config
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000