apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  lables:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"

